@startuml
hide circle
skinparam classAttributeIconSize 0
skinparam backgroundcolor transparent
abstract class Pièce <<abstract>> {
    +estBlanche: bool
    +void {abstract} déplacer(Vector destination)
    -void capturer(Pièce capturée)
}
class Cavalier {
    +void déplacer(Vector destination)
}
class Dame {
    +void déplacer(Vector destination)
}

Pièce <|-- Cavalier
Pièce <|-- Dame
@enduml