@startuml
hide circle
allow_mixing
skinparam classAttributeIconSize 0
skinparam backgroundcolor transparent

folder Utilisateurs
folder Reunions
folder ConnectionServeur

Utilisateurs..>Reunions:<<import>>
Utilisateurs..>ConnectionServeur:<<access>>


@enduml