@startuml
skinparam backgroundcolor transparent
actor ActeurGénérique
actor Acteur1
actor Acteur2

usecase CasGénérique
usecase CasUtilisation1
usecase CasUtilisation2


ActeurGénérique -r-- CasGénérique
Acteur1 -r-- CasUtilisation1
Acteur2 -r-- CasUtilisation2

Acteur1 --|> ActeurGénérique
Acteur2 -u-|> ActeurGénérique

@enduml