@startuml
skinparam backgroundcolor transparent
hide circle
skinparam classAttributeIconSize 0

class Voiture {
  + démarrer(): void 
  + arreter(): void
  + accélérer(float vitesse): void
  + freiner(): void
}

class Moteur {
  - cylindres: int
  - puissance: int
  + démarrer(): void
  + arreter(): void
}

class Roue {
  - taille: int
  - matière: string
  + tourner(): void
}

class Passager {
  - prénom: string
  - nomDeFamille: string
  - /nom: String
  - age: int
  + getNom(): String
  + getAge(): int
}

Voiture "1" --> "1" Moteur 
Voiture "1" --> "4" Roue
Voiture "1" --> "1..5" Passager 

@enduml