@startuml
skinparam backgroundcolor transparent
hide circle
skinparam classAttributeIconSize 0

class Car {
  - engine: Engine
  - wheels: Wheel[4]
  - passengers: Passenger[1..5]
  + start()
  + stop()
  + accelerate(speed: double)
  + brake()
}
@enduml