@startuml
hide circle
skinparam classAttributeIconSize 0

class Car {
  + start()
  + stop()
  + accelerate(speed: double)
  + brake()
}

class Engine {
  - cylinders: int
  - horsepower: int
  + start()
  + stop()
}

class Wheel {
  - size: int
  - material: String
  + rotate()
}

class Passenger {
  - firstName: String
  - lastName: String
  - /name: String
  - age: int
  + getName()
  + getAge()
}

Car -l-> "1" Engine : \t
Car "4" --> "1" Wheel
Car "1..5" -r-> "1" Passenger : \t\t\t\t

@enduml