@startuml
skinparam backgroundcolor transparent
hide circle
skinparam classAttributeIconSize 0

class Voiture {
  - moteur: Moteur
  - roues: roue[4]
  - passagers: Passager[1..5]
  + démarrer()
  + arreter()
  + accélérer(float vitesse)
  + freiner()
}
@enduml