@startuml

class "signal.h" as file1
class "signal.c" as file2
class "alert.h" as file3
class "alarm.h {v=3.0}" as file4
class "alarm.h {v=3.1}" as file5

file2 ..> file1
file1 ..> file3
file4 ..> file3
file5 ..> file4:<<parent>>
@enduml