@startuml
skinparam backgroundcolor transparent
skinparam linetype ortho

node "Serveur Base de données" as DB {
  artifact "BD MySQL"
}

node "Serveur Web" as webServer {
  artifact "Application Web"
}

DB -r-- webServer

@enduml