@startuml
hide circle
skinparam classAttributeIconSize 0
abstract class Véhicule <<abstract>> {
    
}
class Voiture {
    
}
class Scooter {
    
}
class Vélo {
    
}
class Trottinette {
    
}
class Usager {
    
}

class Réserver{}

Véhicule <|-- Voiture
Véhicule <|-- Scooter
Véhicule <|-- Vélo
Véhicule <|-- Trottinette
Véhicule "0..*" - "1..*" Usager 
(Véhicule, Usager) .. Réserver
@enduml