@startuml
skinparam backgroundcolor transparent
skinparam NodeBackgroundColor whitesmoke
skinparam linetype ortho
 
node "Appareil mobile Android" as androidDevice <<device>>{
  node "Android 14" <<executionEnvironment>> {
      artifact "polyAuto.apk"
  }
}



node "Serveur d'application (VM AWS EC2)" as backend <<device>> {
  node "Debian (Linux)" <<executionEnvironment>> {
    artifact serveur.ts
  }
}




node "Serveurs de Google" <<device>> {
  component "GoogleMapsAPI" as gmaps
}






node "Serveurs AWS" as vehic <<device>> {
    node "MongoDB - M0" <<database>> {
      component "PolyAutoCluster"
  }
}

backend --- vehic
androidDevice --d- backend
gmaps - backend

@enduml
