@startuml
skinparam backgroundcolor transparent
skinparam NodeBackgroundColor whitesmoke
skinparam linetype ortho
 
node "Appareil mobile Android" as androidDevice <<device>>{
  node "Android 14" <<executionEnvironment>> {
      artifact "Application Android"
  }
}
node "Serveur d'application" as backend <<device>>
node Véhicules <<database>>
node Services <<database>> {
    artifact "Service d'authentification" as authservice
    artifact "Service de réservation" as bookingservice
    artifact "Service de localisation" as locationservice
    artifact "Service de facturation" as billingservice
}


androidDevice -- backend
backend -- Véhicules
backend -- Services

@enduml
