@startuml
skinparam linetype polyline
 skinparam linetype ortho
 skinparam backgroundcolor transparent

package "PolyAuto" {
    skinparam backgroundcolor transparent
    skinparam classAttributeIconSize 0
    package "Utilisateurs" {
        class Usager
        class PermisSAAQ
        class CompagnieAssurance
    }
    package "Véhicules" {
        abstract class Véhicule
        class Voiture
        class Scooter
        class Vélo
        class Trottinette
    }
    package "Réservations" {
        class Réserver
    }
    package "Géolocalisation" {
        class GéolocalisationService
    }
    
    Usager --> Véhicules
    Réserver --> Usager
    Réserver -> Véhicules
    GéolocalisationService -> Véhicules
}
@enduml
