@startuml
hide circle
skinparam backgroundcolor transparent
skinparam classAttributeIconSize 0
abstract class Véhicule <<abstract>> {
    
}
class Voiture {
    
}
class Scooter {
    
}
class Vélo {
    
}
class Trottinette {
    
}
class Usager {
    - matricule : string
    - permisConduire : PermisConduire
    - assurance : Assurance
    + fournirPreuvePermis() : void
    + fournirPreuveAssurance() : void
}
class PermisConduire {
    - numeroPermis : string
    - paysEmetteur : string
}
class Assurance {
    - numeroAssurance : string
}

class Réserver {
    - véhicule : Véhicule
    - usager : Usager
    - dateDebut : Date
    - dateFin : Date
}

Véhicule <|-- Voiture
Véhicule <|-- Scooter
Véhicule <|-- Vélo
Véhicule <|-- Trottinette
Véhicule "0..*" - "1..*" Usager 
(Véhicule, Usager) .. Réserver
Usager --> PermisConduire
Usager --> Assurance

@enduml
