@startuml
hide circle
skinparam backgroundcolor transparent

component Composant1
component Composant2
rectangle Interface <<Interface>>

Interface <-[dotted]l- Composant1
Interface <|-[dotted]- Composant2
@enduml