@startuml
hide circle
skinparam backgroundcolor transparent

component Component1
component Component2
rectangle Interface <<Interface>>

Interface <-[dotted]l- Component1
Interface <|-[dotted]- Component2
@enduml