@startuml
skinparam backgroundcolor transparent
left to right direction
hide circle
skinparam classAttributeIconSize 0
class Array
class Utilisateur
circle IList

Utilisateur --( IList
IList -- Array
@enduml

