@startuml
hide circle
skinparam backgroundcolor transparent
package Utilisateurs

package "Réunions" as B{
  rectangle "+ Réunion"
  rectangle "- Participants "
}

Utilisateurs -r[dotted]-> B : <<import>>
@enduml