@startuml
hide circle
skinparam backgroundcolor transparent
allow_mixing
skinparam classAttributeIconSize 0

folder Paquetage

class ClasseA{
    ~attribut
}

class ClasseB{
    méthode()
}

ClasseA -u-+ Paquetage
ClasseB -u-+ Paquetage
@enduml