@startuml
skinparam backgroundcolor transparent
[ClientUI]
[ProduitsService] as Comp2
component CommandeService
component [PaiementService] as Comp4
ClientUI .> Comp2
Comp2 ..> CommandeService
Comp2 ..> Comp4
@enduml