@startuml
left to right direction
skinparam backgroundcolor transparent
actor Client as g
Package Employé {
  actor Chef as c
  actor "Critique gastronomique" as fc
}
Rectangle Restaurant {
  usecase "Manger un repas" as UC1
  usecase "Payer l'addition" as UC2
  usecase "Boire" as UC3
  usecase "Émettre une critique" as UC4
}
fc --> UC4
g --> UC1
g --> UC2
g --> UC3
@enduml